spring:
  application:
    name: KnowYourCustomer
  jackson:
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: NON_NULL
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration

server:
  port: ${SERVER_PORT:8000}

 
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: env, health, info, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    git:
      mode: simple

info:
  app:
    version: '@project.version@'
    name: '@project.name@'
        